### Get all staff
GET http://localhost:5000/api/Staff/GetStaff
Accept: application/json

### Get staff member by ID
GET http://localhost:5000/api/Staff/GetStaffMember/1
Accept: application/json

### Get staff member by email
GET http://localhost:5000/api/Staff/GetStaffByEmail/test@example.com
Accept: application/json
