name: Simple Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.x.x
      - name: Build SeatingAPI
        run: dotnet build src/aspire-base/SeatingAPI/SeatingAPI.csproj --configuration Release